INSERT INTO 
	dbo.Products(ID, Name )
VALUES 
	(NEWID(), N'Бумага белая'),
	(NEWID(), N'тетрадь 12, клетка, hello kitty'),
	(NEWID(), N'тетрадь 12, клетка, transformers'),
	(NEWID(), N'тетрадь 12, клетка'),
	(NEWID(), N'Тетрадь, 12 линия, hello kitty'),
	(NEWID(), N'Тетрадь, 12 линия'),
	(NEWID(), N'Тетрадь, 12 линия, transformers'),
	(NEWID(), N'Дневник hello kitty'),
	(NEWID(), N'Дневник transformers'),
	(NEWID(), N'Ежедневник'),
	(NEWID(), N'Дневник'),
	(NEWID(), N'Краски, 12 цв'),
	(NEWID(), N'Краски, 24 цв'),
	(NEWID(), N'Краски, 10 цв'),
	(NEWID(), N'Фломастеры 12шт, Ёжик'),
	(NEWID(), N'Фломастеры 12шт, hello kitty'),
	(NEWID(), N'Фломастеры 12шт, transformers'),
	(NEWID(), N'Цветные карандаши, 8шт'),
	(NEWID(), N'Цветные карандаши, 24шт'),
	(NEWID(), N'Цветные карандаши, 36шт'),
	(NEWID(), N'Ручка синия'),
	(NEWID(), N'Ручка черная'),
	(NEWID(), N'Ручка розовая'),	
	(NEWID(), N'Простой карандаш, hello kitty'),
	(NEWID(), N'Простой карандаш, transformers'),
	(NEWID(), N'Простой карандаш'),
	(NEWID(), N'Папка для тетрадей'),
	(NEWID(), N'Сегрегатор'),
	(NEWID(), N'Файлы, 100шт'),
	(NEWID(), N'Точилка, hello kitty'),
	(NEWID(), N'Точилка transformers'),
	(NEWID(), N'Точилка'),
	(NEWID(), N'Линейка, hello kitty'),
	(NEWID(), N'Линейка transformers'),
	(NEWID(), N'Линейка'),
	(NEWID(), N'Калькулятор')	
GO